  name: gh-pages-deploy-feature

  on:
    push:
      branches:
        - feature
        - release

  jobs:
    publish-docker-images:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build and publish API image
          run: |
            docker build -t sisseradapi:$(basename ${{ github.ref }}) -f Dockerfile.back .
            docker tag sisseradapi:$(basename ${{ github.ref }}) mateus314/sisseradapi:$(basename ${{ github.ref }})
            docker push mateus314/sisseradapi:$(basename ${{ github.ref }})

        - name: Build and publish Front image
          run: |
            docker build -t sisseradfront:$(basename ${{ github.ref }}) -f Dockerfile.front .
            docker tag sisseradfront:$(basename ${{ github.ref }}) mateus314/sisseradfront:$(basename ${{ github.ref }})
            docker push mateus314/sisseradfront:$(basename ${{ github.ref }})


    
